# Generated by Django 4.1.3 on 2022-11-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_leite_leiteprecos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='leitePrecos',
            new_name='leitePreco',
        ),
    ]
