# Generated by Django 4.1.3 on 2022-11-14 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_leiteprecos_leitepreco'),
    ]

    operations = [
        migrations.AddField(
            model_name='leitepreco',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leitepreco',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
