# Generated by Django 4.1.3 on 2022-11-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_leitepreco_data_leitepreco_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leitepreco',
            old_name='descricao',
            new_name='coments',
        ),
        migrations.AddField(
            model_name='leitepreco',
            name='producao',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leitepreco',
            name='unidade',
            field=models.CharField(default=1000, max_length=20),
            preserve_default=False,
        ),
    ]
